### ISSUE TITLE
MasterCard\Core\Exception\ApiException Object | Unauthorized

### ISSUE THREAD

**Issue by monwabisi** [MasterCard/sdk-core-php#3]
Hi all, I keep getting an Unauthorized message whenever I try to connect with the API. I'm running a test in the sandbox environment.

2017-09-06 07:23:22] ApiController.DEBUG: <<body: {"error":{"code":"openapi.invalid.xclient.id","message":""},"reference":"Ae04de.jcl2dal45/-"} [] []
[2017-09-06 07:23:22] ApiController.DEBUG: --------------------- [] []
HttpStatus: ()
Message: ()
ReasonCode: ()
Source: ()
MasterCard\Core\Exception\ApiException Object
(
    [message:protected] => Unauthorized
    [rawErrorData:protected] => MasterCard\Core\Model\RequestMap Object
        (
            [properties:protected] => Array
                (
                    [error] => Array
                        (
                            [code] => openapi.invalid.xclient.id
                            [message] =>
                        )..................................

**Comment by ade90036** [comment]
What service is this?

It seems thats a message originated from our backend serivce.

Ade

**Comment by monwabisi** [comment]
"What service is this?" -I'm using Qkr.....?
I think the error is a result of me not following the guide properly, I generated a new SandBox key and did not request approval. I think that's what is causing the error, so I'll close this issue and wait for approval of the new key, if it persists afterwards then I'll re-open.

**Comment by ade90036** [comment]
Sandbox should work without the need to approve the key. Key needs to be
approved / (move to production) only for production environment.

Could you raise an ticket by in support menu @ developer.mastercard.com

It seems that there is something wrong with qkr backed service.

**Comment by monwabisi** [comment]
Will do, thanks.
