### ISSUE TITLE
Errorcode: Issue with order reference

### ISSUE THREAD

**Issue by foreigntalent** [MasterCard/sdk-core-php#9]
Hi Guys, 

I am new here but hopefully someone can point us to the right way because it seems we are stuck at the very last moment of successful transaction after inputting the "OTP".

We checked and the error code since to suggest that we didnt do the correct thing with reference id inside our API.

Any suggestions on this issue?

Thanks.

Bob

**Comment by namaggarwal** [comment]
Which API are you using ?

**Comment by foreigntalent** [comment]
Dear Sir,

 

Thank you for getting back to me. We tried using isenselab’s API (MPGS) to integrate with opencart but the bank told us they don't allow the use of “webhook notification secret” so their MPGS API couldn't work. It is a compulsory selection and Isenselab insisted they couldn't modify the MPGS API to switch that off.

 

After which we had to use the source code from the bank which gave us issues because reference id for the order couldn't be send to the MA so everything can be seen inside the MA except the reference column of the transactions….

 

Any suggestions would be most appreciated.

 

Thanks.

 

Bob

 

发件人: noreply@github.com <noreply@github.com> 代表 Naman Aggarwal
发送时间: 2018年8月22日 13:57
收件人: Mastercard/sdk-core-php <sdk-core-php@noreply.github.com>
抄送: foreigntalent <shenzhen_bt2@126.com>; Author <author@noreply.github.com>
主题: Re: [Mastercard/sdk-core-php] Errorcode: Issue with order reference (#9)

 

Which API are you using ?

**Comment by kkrauth** [comment]
Looks like you have a service specific question rather than an SDK issue. Can you please go to https://developer.mastercard.com/support and click the "Request Help" button at the bottom of the page? They will put you in touch with the right people to troubleshoot the issue you are experiencing.

**Comment by foreigntalent** [comment]
Hi Kosta,

 

Any chance we can cross examine the API here because we did try developer support but nothing feedback to us for now?

 

I can forward the php files to double check.

 

Many thanks.

 

Bob

 

 

 

 

发件人: noreply@github.com <noreply@github.com> 代表 Kosta Krauth
发送时间: 2018年8月23日 1:13
收件人: Mastercard/sdk-core-php <sdk-core-php@noreply.github.com>
抄送: foreigntalent <shenzhen_bt2@126.com>; Author <author@noreply.github.com>
主题: Re: [Mastercard/sdk-core-php] Errorcode: Issue with order reference (#9)

 

Looks like you have a service specific question rather than an SDK issue. Can you please go to https://developer.mastercard.com/support and click the "Request Help" button at the bottom of the page? They will put you in touch with the right people to troubleshoot the issue you are experiencing.

**Comment by jaaufauvre** [comment]
Closing this old issue.
